version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    post_build:
      commands:
        - mvn package
        - mv target/spaceappspring.war spaceappspring.war
artifacts:
  files:
    - spaceappspring.war
    - .ebextensions/**/*
  base-directory: 'target/spaceappspring'