version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo installing maven...
      - apt-get update -y
      - apt-get install -y maven
    build:
      commands:
        - echo building spaceapp backend
        - mvn install
    post_build:
       commands:
         - mvn package
artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'